/* Generated By:JavaCC: Do not edit this line. MiniJavaConstants.java */
package Parse;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MiniJavaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ABSTRACT = 6;
  /** RegularExpression Id. */
  int MAIN = 7;
  /** RegularExpression Id. */
  int BREAK = 8;
  /** RegularExpression Id. */
  int CASE = 9;
  /** RegularExpression Id. */
  int CATCH = 10;
  /** RegularExpression Id. */
  int CLASS = 11;
  /** RegularExpression Id. */
  int CONST = 12;
  /** RegularExpression Id. */
  int CONTINUE = 13;
  /** RegularExpression Id. */
  int _DEFAULT = 14;
  /** RegularExpression Id. */
  int DO = 15;
  /** RegularExpression Id. */
  int ELSE = 16;
  /** RegularExpression Id. */
  int EXTENDS = 17;
  /** RegularExpression Id. */
  int FALSE = 18;
  /** RegularExpression Id. */
  int FINAL = 19;
  /** RegularExpression Id. */
  int FINALLY = 20;
  /** RegularExpression Id. */
  int FOR = 21;
  /** RegularExpression Id. */
  int GOTO = 22;
  /** RegularExpression Id. */
  int IF = 23;
  /** RegularExpression Id. */
  int IMPLEMENTS = 24;
  /** RegularExpression Id. */
  int IMPORT = 25;
  /** RegularExpression Id. */
  int INSTANCEOF = 26;
  /** RegularExpression Id. */
  int INTERFACE = 27;
  /** RegularExpression Id. */
  int NATIVE = 28;
  /** RegularExpression Id. */
  int NEW = 29;
  /** RegularExpression Id. */
  int NULL = 30;
  /** RegularExpression Id. */
  int PACKAGE = 31;
  /** RegularExpression Id. */
  int PRIVATE = 32;
  /** RegularExpression Id. */
  int PROTECTED = 33;
  /** RegularExpression Id. */
  int PUBLIC = 34;
  /** RegularExpression Id. */
  int RETURN = 35;
  /** RegularExpression Id. */
  int STATIC = 36;
  /** RegularExpression Id. */
  int SUPER = 37;
  /** RegularExpression Id. */
  int SWITCH = 38;
  /** RegularExpression Id. */
  int SYNCHRONIZED = 39;
  /** RegularExpression Id. */
  int THIS = 40;
  /** RegularExpression Id. */
  int THROW = 41;
  /** RegularExpression Id. */
  int THROWS = 42;
  /** RegularExpression Id. */
  int TRANSIENT = 43;
  /** RegularExpression Id. */
  int THREAD = 44;
  /** RegularExpression Id. */
  int TRUE = 45;
  /** RegularExpression Id. */
  int TRY = 46;
  /** RegularExpression Id. */
  int VOID = 47;
  /** RegularExpression Id. */
  int VOLATILE = 48;
  /** RegularExpression Id. */
  int WHILE = 49;
  /** RegularExpression Id. */
  int BOOLEAN = 50;
  /** RegularExpression Id. */
  int BYTE = 51;
  /** RegularExpression Id. */
  int CHAR = 52;
  /** RegularExpression Id. */
  int DOUBLE = 53;
  /** RegularExpression Id. */
  int FLOAT = 54;
  /** RegularExpression Id. */
  int INT = 55;
  /** RegularExpression Id. */
  int LONG = 56;
  /** RegularExpression Id. */
  int SHORT = 57;
  /** RegularExpression Id. */
  int String = 58;
  /** RegularExpression Id. */
  int ASSIGN = 59;
  /** RegularExpression Id. */
  int GT = 60;
  /** RegularExpression Id. */
  int LT = 61;
  /** RegularExpression Id. */
  int BANG = 62;
  /** RegularExpression Id. */
  int TILDE = 63;
  /** RegularExpression Id. */
  int HOOK = 64;
  /** RegularExpression Id. */
  int COLON = 65;
  /** RegularExpression Id. */
  int EQ = 66;
  /** RegularExpression Id. */
  int LE = 67;
  /** RegularExpression Id. */
  int GE = 68;
  /** RegularExpression Id. */
  int NE = 69;
  /** RegularExpression Id. */
  int SC_OR = 70;
  /** RegularExpression Id. */
  int SC_AND = 71;
  /** RegularExpression Id. */
  int INCR = 72;
  /** RegularExpression Id. */
  int DECR = 73;
  /** RegularExpression Id. */
  int PLUS = 74;
  /** RegularExpression Id. */
  int MINUS = 75;
  /** RegularExpression Id. */
  int STAR = 76;
  /** RegularExpression Id. */
  int SLASH = 77;
  /** RegularExpression Id. */
  int BIT_AND = 78;
  /** RegularExpression Id. */
  int BIT_OR = 79;
  /** RegularExpression Id. */
  int XOR = 80;
  /** RegularExpression Id. */
  int REM = 81;
  /** RegularExpression Id. */
  int LSHIFT = 82;
  /** RegularExpression Id. */
  int RSIGNEDSHIFT = 83;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFT = 84;
  /** RegularExpression Id. */
  int PLUSASSIGN = 85;
  /** RegularExpression Id. */
  int MINUSASSIGN = 86;
  /** RegularExpression Id. */
  int STARASSIGN = 87;
  /** RegularExpression Id. */
  int SLASHASSIGN = 88;
  /** RegularExpression Id. */
  int ANDASSIGN = 89;
  /** RegularExpression Id. */
  int ORASSIGN = 90;
  /** RegularExpression Id. */
  int XORASSIGN = 91;
  /** RegularExpression Id. */
  int REMASSIGN = 92;
  /** RegularExpression Id. */
  int LSHIFTASSIGN = 93;
  /** RegularExpression Id. */
  int RSIGNEDSHIFTASSIGN = 94;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFTASSIGN = 95;
  /** RegularExpression Id. */
  int LPAREN = 96;
  /** RegularExpression Id. */
  int RPAREN = 97;
  /** RegularExpression Id. */
  int LBRACE = 98;
  /** RegularExpression Id. */
  int RBRACE = 99;
  /** RegularExpression Id. */
  int LBRACKET = 100;
  /** RegularExpression Id. */
  int RBRACKET = 101;
  /** RegularExpression Id. */
  int SEMICOLON = 102;
  /** RegularExpression Id. */
  int QUOTE = 103;
  /** RegularExpression Id. */
  int APOSTROPHE = 104;
  /** RegularExpression Id. */
  int DOT = 105;
  /** RegularExpression Id. */
  int COMMA = 106;
  /** RegularExpression Id. */
  int XINU = 107;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 111;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 112;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 113;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 115;
  /** RegularExpression Id. */
  int CHARACTER_LITERAL = 116;
  /** RegularExpression Id. */
  int STRING_LITERAL = 117;
  /** RegularExpression Id. */
  int ID = 118;
  /** RegularExpression Id. */
  int LETTER = 119;
  /** RegularExpression Id. */
  int DIGIT = 120;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_SINGLE_LINE_COMMENT = 1;
  /** Lexical state. */
  int IN_FORMAL_COMMENT = 2;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"abstract\"",
    "\"main\"",
    "\"break\"",
    "\"case\"",
    "\"catch\"",
    "\"class\"",
    "\"const\"",
    "\"continue\"",
    "\"default\"",
    "\"do\"",
    "\"else\"",
    "\"extends\"",
    "\"false\"",
    "\"final\"",
    "\"finally\"",
    "\"for\"",
    "\"goto\"",
    "\"if\"",
    "\"implements\"",
    "\"import\"",
    "\"instanceof\"",
    "\"interface\"",
    "\"native\"",
    "\"new\"",
    "\"null\"",
    "\"package\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"return\"",
    "\"static\"",
    "\"super\"",
    "\"switch\"",
    "\"synchronized\"",
    "\"this\"",
    "\"throw\"",
    "\"throws\"",
    "\"transient\"",
    "\"thread\"",
    "\"true\"",
    "\"try\"",
    "\"void\"",
    "\"volatile\"",
    "\"while\"",
    "\"boolean\"",
    "\"byte\"",
    "\"char\"",
    "\"double\"",
    "\"float\"",
    "\"int\"",
    "\"long\"",
    "\"short\"",
    "\"String\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\">>\"",
    "\">>>\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\"\\\"\"",
    "\"\\\'\"",
    "\".\"",
    "\",\"",
    "\"Xinu\"",
    "\"//\"",
    "<token of kind 109>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 114>",
    "<INTEGER_LITERAL>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<ID>",
    "<LETTER>",
    "<DIGIT>",
    "<token of kind 121>",
  };

}
